baseURL = "https://reader.117302.xyz/"
title = "Reader"
theme = "jane"
languageCode = "en"
defaultContentLanguage = "en"
hasCJKLanguage = false
enableRobotsTXT = true
enableEmoji = true
paginate = 10

[author]
  name = "Your Name"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

[[menu.main]]
  name = "Categories"
  weight = 40
  identifier = "categories"
  url = "/categories/"

[params]
  math = true
  mathEngine = "katex"  # or "mathjax"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
